// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aphdwuvkzxhkldhvawng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaGR3dXZrenhoa2xkaHZhd25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjA2MjksImV4cCI6MjA2NTg5NjYyOX0.wNifz6H1k8vykCJotyQYiHbwR-bvuqcVpsHnMAwUkZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);